// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function GetInstalledServices():Promise<Array<service.ServiceInfo>>;

export function GetServiceConfig(arg1:string):Promise<service.ServiceConfig>;

export function GetServiceStatus(arg1:string):Promise<string>;

export function InstallService(arg1:service.ServiceConfig):Promise<void>;

export function LoadConfigFromFile(arg1:string):Promise<Array<service.ServiceConfig>>;

export function ModifyService(arg1:string,arg2:service.ServiceConfig):Promise<void>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function RemoveService(arg1:string):Promise<void>;

export function RestartService(arg1:string):Promise<void>;

export function SaveConfigToFile(arg1:string):Promise<void>;

export function ShowOpenDialog(arg1:string):Promise<string>;

export function ShowSaveDialog(arg1:string,arg2:string):Promise<string>;

export function StartService(arg1:string):Promise<void>;

export function StopService(arg1:string):Promise<void>;
